"use client";
import { useState, type FormEvent, type ChangeEvent } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { Upload, ArrowUpRight, LogOut, Pencil, Trash2, Plus, Search, LoaderCircle, Download } from "lucide-react";
import type { Game } from "@/db/schema";
import type { CatalogData } from "@/components/Catalog";
const EMPTY = { title: "", slug: "", tagline: "", description: "", category: "Arcade", tags: "", accent: "#d4f76b", accent2: "#769333", coverUrl: "", source: "local", url: "", controls: "Arrow keys / WASD", weight: "light", status: "soon", sortOrder: 50 };
type Form = typeof EMPTY;
export default function AdminConsole({ initial, subscribers }: { initial: CatalogData; subscribers: number }) {
  const [data,setData]=useState(initial),[form,setForm]=useState<Form>({...EMPTY}),[editing,setEditing]=useState<string|null>(null),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[deleting,setDeleting]=useState<Game|null>(null),[search,setSearch]=useState("");const router=useRouter();
  const slug=(form.slug||form.title).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100);
  const set=(key:keyof Form)=>(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm((f)=>({...f,[key]:key==="sortOrder"?Number(e.target.value):e.target.value}));
  async function refresh(page=1){const res=await fetch(`/api/games?limit=24&page=${page}&q=${encodeURIComponent(search)}`);if(!res.ok)throw new Error("Could not load games.");setData(await res.json());}
  function clear(){setForm({...EMPTY});setEditing(null);setFile(null);}
  function edit(game:Game){setEditing(game.slug);setFile(null);setError("");setMessage("");setForm({title:game.title,slug:game.slug,tagline:game.tagline,description:game.description,category:game.category,tags:game.tags,accent:game.accent,accent2:game.accent2,coverUrl:game.coverUrl||"",source:game.source,url:game.url||"",controls:game.controls,weight:game.weight,status:game.status,sortOrder:game.sortOrder});window.scrollTo({top:0,behavior:"smooth"});}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");setError("");try{
    if(file&&form.source==="local"){const payload=new FormData();payload.set("file",file);payload.set("slug",slug);const upload=await fetch("/api/admin/upload",{method:"POST",body:payload});const result=await upload.json();if(!upload.ok)throw new Error(result.error||"Upload failed.");}
    const res=await fetch(editing?`/api/games/${editing}`:"/api/games",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,slug})});const result=await res.json();if(!res.ok)throw new Error(result.error||"Could not save the game.");setMessage(`${result.game.title} saved. ${result.game.status==="live"?"Ready to play.":"Coming-soon page is ready."}`);clear();await refresh();
  }catch(e){setError(e instanceof Error?e.message:"Could not save. Try again.");}finally{setBusy(false);}}
  async function updateStatus(game:Game){setBusy(true);setError("");try{const res=await fetch(`/api/games/${game.slug}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:game.status==="live"?"soon":"live"})});const result=await res.json();if(!res.ok)throw new Error(result.error);await refresh(data.page);}catch(e){setError(e instanceof Error?e.message:"Could not change status.");}finally{setBusy(false);}}
  async function remove(){if(!deleting)return;setBusy(true);try{const res=await fetch(`/api/games/${deleting.slug}`,{method:"DELETE"});if(!res.ok)throw new Error();setDeleting(null);await refresh();}catch{setError("Could not delete this game.");}finally{setBusy(false);}}
  async function logout(){await fetch("/api/admin/session",{method:"DELETE"});router.refresh();}
  return <div className="admin-page"><div className="admin-top"><div><span className="eyebrow">BACKSTAGE / PUBLISHER ACCESS</span><h1>The creator studio<span className="lime">.</span></h1><p>Your games. Your domain. ZIP a web build with a root index.html, add its details, and publish. Uploads are capped at 30 MB compressed; larger builds can be deployed directly to your game storage.</p></div><button className="btn btn-outline" onClick={logout}><LogOut size={14}/>Sign out</button></div>
    <div className="admin-layout"><form className="admin-card" onSubmit={submit}><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline"}}><h2>{editing?"Fine-tune your game.":"Make room for a new game."}</h2>{editing&&<button type="button" className="icon-button" title="New game" aria-label="Start a new game entry" onClick={clear}><Plus size={19}/></button>}</div><div className="admin-grid"><Field label="TITLE"><input required maxLength={160} value={form.title} onChange={set("title")}/></Field><Field label="SLUG / PERMANENT LINK"><input value={form.slug} onChange={set("slug")} disabled={Boolean(editing)} placeholder={slug||"auto-from-title"}/></Field></div><Field label="ONE-LINE TAGLINE"><input value={form.tagline} maxLength={240} onChange={set("tagline")}/></Field><Field label="DESCRIPTION"><textarea value={form.description} onChange={set("description")}/></Field><div className="admin-grid"><Field label="CATEGORY"><input required value={form.category} onChange={set("category")}/></Field><Field label="TAGS / COMMA SEPARATED"><input value={form.tags} onChange={set("tags")}/></Field></div><Field label="COVER IMAGE URL"><input value={form.coverUrl} onChange={set("coverUrl")} placeholder="/images/cover.png or https://…"/></Field><div className="admin-grid"><Field label="DELIVERY"><select value={form.source} onChange={set("source")}><option value="local">Same domain · recommended</option><option value="embed">External iframe</option><option value="external">External new tab</option></select></Field><Field label="AVAILABILITY"><select value={form.status} onChange={set("status")}><option value="soon">Coming soon</option><option value="live">Live / playable</option><option value="maintenance">Maintenance</option></select></Field></div>
      {form.source==="local"?<><Field label="GAME BUILD / ZIP, MAX 30 MB"><input key={`${editing||"new"}:${message}`} type="file" accept=".zip,application/zip" onChange={(e)=>setFile(e.target.files?.[0]||null)}/></Field><p className="admin-hint"><Upload size={13} style={{display:"inline",marginRight:6}}/>Upload a build ZIP, or deploy files to <code>public/games/{slug||"your-slug"}/index.html</code>. Use relative asset paths. Only publish builds you trust.</p></>:<Field label="HTTPS GAME URL"><input type="url" required value={form.url} onChange={set("url")} placeholder="https://…"/></Field>}
      <Field label="CONTROLS"><input value={form.controls} onChange={set("controls")}/></Field><div className="admin-grid"><Field label="ACCENT COLOR"><input type="color" value={form.accent} onChange={set("accent")}/></Field><Field label="SORT ORDER / LOWEST FIRST"><input type="number" min="0" max="100000" value={form.sortOrder} onChange={set("sortOrder")}/></Field></div><button className="btn btn-lime" style={{width:"100%"}} disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/>Saving…</>:<>{editing?"Save changes":"Add to the collection"}<ArrowUpRight size={16}/></>}</button>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="admin-message" role="status">{message}</p>}</form>
      <section className="admin-card"><h2>The collection / {data.total}</h2><form onSubmit={(e)=>{e.preventDefault();void refresh().catch(()=>setError("Could not search games."));}} style={{display:"flex",gap:8}}><label style={{flex:1}}><span className="sr-only">Search the catalogue</span><input className="admin-search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search the catalogue…"/></label><button className="icon-button" aria-label="Search catalogue"><Search size={18}/></button></form>{data.games.map((g)=><div key={g.slug} className="admin-list-item">{g.coverUrl&&<div className="admin-thumb"><Image src={g.coverUrl} alt="" fill sizes="65px" className="cover-image"/></div>}<div className="admin-list-info"><strong>{g.title}</strong><span className="mono">{g.status.toUpperCase()} · {g.plays} PLAYS</span></div><div className="admin-list-actions"><button type="button" disabled={busy} onClick={()=>void updateStatus(g)}>{g.status==="live"?"Unpublish":"Publish"}</button><button type="button" onClick={()=>edit(g)} aria-label={`Edit ${g.title}`} title="Edit"><Pencil size={12}/></button><button type="button" onClick={()=>setDeleting(g)} aria-label={`Delete ${g.title}`} title="Delete"><Trash2 size={12}/></button></div></div>)}{deleting&&<div className="admin-delete" role="alert">Remove “{deleting.title}” from the catalogue? This cannot be undone.<div><button onClick={()=>setDeleting(null)}>Keep it</button><button disabled={busy} onClick={()=>void remove()}>Yes, remove it</button></div></div>}<div className="admin-meta"><span>Page {data.page}</span><div style={{display:"flex",gap:15}}>{data.page>1&&<button onClick={()=>void refresh(data.page-1)}>← Previous</button>}{data.hasMore&&<button onClick={()=>void refresh(data.page+1)}>Next →</button>}</div></div><div style={{marginTop:28,borderTop:"1px solid #425630",paddingTop:23}}><h2>People waiting for the next drop.</h2><p className="admin-hint">{subscribers} release signups. Export the list to your email service. This site records opt-ins; it does not send emails automatically.</p><a href="/api/admin/subscribers" className="btn btn-outline"><Download size={14}/>Export opt-ins</a></div><div className="admin-meta" style={{marginTop:30}}><a href="/why-ads">Monetisation setup <ArrowUpRight size={12} style={{display:"inline"}}/></a><a href="/">View the site <ArrowUpRight size={12} style={{display:"inline"}}/></a></div></section></div></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="admin-field"><span>{label}</span>{children}</label>;}
