"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { LockKeyhole, ArrowRight, LoaderCircle } from "lucide-react";
export default function AdminLogin({ configured }: { configured: boolean }) {
  const [secret, setSecret] = useState(""); const [error,setError] = useState(""); const [busy,setBusy]=useState(false); const router=useRouter();
  async function submit(e: FormEvent) { e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({secret})});const data=await res.json();if(!res.ok)throw new Error(data.error);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not sign in.");}finally{setBusy(false);} }
  return <div className="admin-page"><div className="admin-top"><div><span className="eyebrow">FOR THE PEOPLE WHO MAKE THE GOOD STUFF</span><h1>The creator studio<span className="lime">.</span></h1><p>One game or one thousand. Same simple setup: upload a web build, add a cover, and publish.</p></div></div><div className="admin-card admin-login"><LockKeyhole size={29}/><h2>A little backstage access.</h2><p>{configured?"Sign in with your publisher access key. This area controls the public catalogue and is never open to visitors.":"Publishing is safely locked until an owner access key is configured. Set ADMIN_SECRET to a private value of at least 16 characters in your server environment, then restart the app."}</p>{configured?<form onSubmit={submit}><label className="admin-field">PUBLISHER ACCESS KEY<input type="password" value={secret} onChange={(e)=>setSecret(e.target.value)} required autoComplete="current-password" /></label><button className="btn btn-lime" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<>Enter the studio <ArrowRight size={16}/></>}</button>{error&&<p className="form-error" role="alert">{error}</p>}</form>:<div className="admin-setup">1. Configure ADMIN_SECRET<br/>2. Restart the application<br/>3. Sign in here with your key</div>}</div></div>;
}
