"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Check, Trash2 } from "lucide-react";
export default function PrivacyControls() {
  const [optedOut,setOptedOut]=useState(false),[message,setMessage]=useState(""),[email,setEmail]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{try{setOptedOut(localStorage.getItem("klyqo:ads-optout")==="1");}catch{}},[]);
  function toggle(){try{localStorage.setItem("klyqo:ads-optout",optedOut?"0":"1");location.reload();}catch{setMessage("Your browser is blocking local preferences.");}}
  function clear(){try{for(const key of Object.keys(localStorage))if(key.startsWith("klyqo:")&&key!=="klyqo:ads-optout")localStorage.removeItem(key);setMessage("Your on-device game history, saved games and best scores have been cleared. Reload the page to update your library.");}catch{setMessage("Your browser is blocking local storage.");}}
  async function remove(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const res=await fetch("/api/subscribe",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});if(!res.ok)throw new Error();setMessage("If this email was on a release list, it has now been removed from this site’s database.");setEmail("");}catch{setMessage("Could not process that request. Please check the email and try again.");}finally{setBusy(false);}}
  return <><div className="preference-row"><div><h3>{optedOut?"Display ads are off on this device.":"Your advertising preference."}</h3><p>This control stops future AdSense requests here. Consent choices with advertising providers are separate.</p></div><button className="btn btn-outline" onClick={toggle}>{optedOut?<><Check size={15}/>Allow page ads</>:"Disable page ads"}</button></div><div className="preference-row"><div><h3>A fresh start.</h3><p>Clear favourites, recent games and personal bests on this device. Publicly submitted scores are separate.</p></div><button className="btn btn-outline" onClick={clear}><Trash2 size={15}/>Clear local data</button></div><div className="text-section"><h3>Leave the release list.</h3><p>Remove your email from all upcoming-game signup lists stored on this site.</p><form onSubmit={remove} className="release-form"><div className="signup-input-row"><label className="sr-only" htmlFor="remove-email">Email to remove</label><input id="remove-email" type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="Your email address"/><button className="btn btn-outline" disabled={busy}>{busy?"Removing…":"Remove my email"}</button></div></form></div>{message&&<p className="admin-message" role="status">{message}</p>}</>;
}
