const { chromium, expect } = require('@playwright/test');
const fs = require('node:fs/promises');
const base = process.env.TEST_BASE_URL || 'http://localhost:3000';
(async () => {
  await fs.mkdir('artifacts', { recursive: true });
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const errors = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
    page.on('pageerror', (e) => errors.push(e.message));
    await page.goto(base, { waitUntil: 'networkidle' });
    await expect(page.locator('.game-card')).toHaveCount(6);
    await page.screenshot({ path: 'artifacts/desktop.png' });
    await page.screenshot({ path: 'artifacts/desktop-full.png', fullPage: true });
    await page.getByRole('link', { name: 'Play Snake ’97', exact: true }).click();
    await expect(page.locator('dialog[open]')).toHaveCount(1);
    await page.waitForTimeout(2350);
    const snake = page.frameLocator('iframe.game-frame');
    await expect(snake.locator('#board')).toBeVisible();
    await snake.locator('body').press('Space');
    await page.screenshot({ path: 'artifacts/snake-player.png' });
    if (new URL(page.url()).pathname !== '/') throw new Error('Game launch navigated away from the catalogue.');
    await page.getByRole('button', { name: 'Enter fullscreen', exact: true }).click();
    await page.waitForTimeout(200);
    const fullscreen = await page.evaluate(() => Boolean(document.fullscreenElement));
    console.log('Fullscreen API active:', fullscreen);
    await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click();
    await page.getByRole('button', { name: 'Close player', exact: true }).click();
    await page.getByRole('link', { name: 'Play Tetris', exact: true }).click();
    await page.waitForTimeout(2300);
    const tetris = page.frameLocator('iframe.game-frame');
    await tetris.locator('body').press('Space');
    const dropScore = Number(await tetris.locator('#score').textContent());
    if (dropScore <= 0) throw new Error('Tetris hard drop did not update score.');
    await tetris.locator('body').press('p');
    await page.screenshot({ path: 'artifacts/tetris-player.png' });
    console.log('Tetris hard drop score:', dropScore);
    await tetris.locator('body').press('Escape');
    await expect(page.locator('dialog[open]')).toHaveCount(0);
    await page.getByRole('textbox', { name: 'Search games', exact: true }).fill('tetris');
    await expect(page.locator('.game-card')).toHaveCount(1);
    await expect(page.locator('.game-card h3')).toHaveText('Tetris');
    await page.getByRole('textbox', { name: 'Search games', exact: true }).fill('');
    await expect(page.locator('.game-card')).toHaveCount(6);
    await page.getByRole('button', { name: 'Save Snake ’97 to library', exact: true }).click();
    await page.getByRole('button', { name: /^My library/ }).click();
    await expect(page.locator('.game-card')).toHaveCount(1);
    await expect(page.locator('.game-card h3')).toHaveText('Snake ’97');
    await page.getByRole('button', { name: 'Discover', exact: true }).click();
    await expect(page.locator('.game-card')).toHaveCount(6);
    await page.getByRole('link', { name: 'Explore Midnight Drift, coming soon', exact: true }).click();
    await expect(page.locator('dialog[open] iframe')).toHaveCount(0);
    const email = `smoke-${Date.now()}@example.com`;
    await page.locator('.coming-signup input[type=email]').fill(email);
    await page.locator('.coming-signup input[type=checkbox]').check();
    await page.locator('.coming-signup button[type=submit]').click();
    await expect(page.locator('.coming-signup .signup-success')).toBeVisible();
    await page.screenshot({ path: 'artifacts/coming-soon.png' });
    await page.getByRole('button', { name: 'Close player', exact: true }).click();
    const unsub = await page.request.delete(base + '/api/subscribe', { data: { email } });
    if (!unsub.ok()) throw new Error('Could not remove test signup.');
    const unauth = await page.request.post(base + '/api/games', { data: { title: 'Should not publish' } });
    if (unauth.status() !== 401) throw new Error('Public publishing is not blocked.');
    const invalidScore = await page.request.post(base + '/api/games/snake/scores', { data: { score: -1 } });
    if (invalidScore.status() !== 400) throw new Error('Invalid score accepted.');
    const results = await (await page.request.get(base + '/api/games?status=live')).json();
    if (results.total !== 2) throw new Error('Expected exactly two playable demos.');
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
    mobile.on('pageerror', (e) => errors.push('mobile: ' + e.message));
    await mobile.goto(base, { waitUntil: 'networkidle' });
    await mobile.screenshot({ path: 'artifacts/mobile.png' });
    await mobile.screenshot({ path: 'artifacts/mobile-full.png', fullPage: true });
    if (await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Mobile layout overflows horizontally.');
    await mobile.getByRole('link', { name: 'Play Snake ’97', exact: true }).click();
    await mobile.waitForTimeout(2300);
    const touchGame = mobile.frameLocator('iframe.game-frame');
    await expect(touchGame.getByRole('button', { name: 'Move up', exact: true })).toBeVisible();
    await touchGame.getByRole('button', { name: 'Move up', exact: true }).tap();
    await touchGame.getByRole('button', { name: 'Pause game', exact: true }).tap();
    await mobile.screenshot({ path: 'artifacts/mobile-player.png' });
    await mobile.getByRole('button', { name: 'Close player', exact: true }).tap();
    console.log('Browser errors:', errors);
    if (errors.length) throw new Error('Unexpected browser errors.');
    console.log('PASS: desktop/mobile layouts, launch-in-place, fullscreen, Snake, Tetris, search, favourites, coming-soon signup, removal, and API guards.');
  } finally { await browser.close(); }
})().catch((e) => { console.error(e); process.exitCode = 1; });
